name: check_sum_flutter
version: 1.0.4+4
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  webview_flutter: ^4.7.0
  # dart_openai: ^5.1.0
  flutter_easyloading: ^3.0.5
  package_info_plus: ^6.0.0
  shared_preferences: ^2.2.2
  dart_openai: ^1.9.1
  google_fonts: ^4.0.4

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
